import { Box, Typography } from '@mui/material'

const TermsAndConditions = () => {
  return <Box className="h-full overflow-auto p-8">
    <Typography>Effective as of October 8th, 2024.</Typography>
    <Typography variant='h6' className='py-4'>PLEASE READ THIS LICENSE AGREEMENT CAREFULLY BEFORE USING "IMPERSON". BY DOWNLOADING, INSTALLING, OR OTHERWISE USING THIS TOOL, YOU AGREE TO BE BOUND BY THE TERMS OF THIS AGREEMENT.</Typography>
    <Typography>This License Agreement (the “Agreement”) governs the use of the software product "Imperson," which is a tool designed to simulate the speech and behavior of non-playable characters (NPCs) for use in role-playing games (RPGs). By using Imperson (hereafter "the Tool"), you, the user, agree to the following terms and conditions.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>1. GRANT OF LICENSE</Typography>
      <Typography>Subject to the terms of this Agreement, the developer of Imperson (hereafter "Licensor") grants you, the user, a limited, non-exclusive, non-transferable license to use the Tool for personal, non-commercial purposes solely in connection with RPGs. This license does not allow you to use the Tool for any illegal, unethical, or unauthorized purposes.</Typography>
      <Typography>You may not use the Tool to impersonate or replicate any third-party materials that are licensed, copyrighted, trademarked, or otherwise protected under intellectual property laws, unless you have obtained appropriate licenses or permissions for such use.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>2. USER RESPONSIBILITY</Typography>
      <Typography>By using the Tool, you acknowledge that you are solely responsible for the content and outcomes of the conversations generated by the Tool. Any inappropriate, offensive, or harmful speech produced by the Tool is a result of your usage, and not the fault or responsibility of the Licensor. The Tool may generate content that includes profanities, improper language, or content that may be deemed inappropriate by certain audiences. You are responsible for ensuring that the use of such content is lawful in your region and acceptable in the context in which the Tool is being used.</Typography>
      <Typography>You agree that you will not use the Tool in a manner that violates any applicable laws or regulations, and that you are responsible for any consequences that arise from the misuse of the Tool, including, but not limited to, legal and financial liabilities. The Licensor is not liable for any damages arising from the use or misuse of the Tool, including any violations of third-party rights or legal issues that may result from user-generated content.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>3. CONTENT GENERATION DISCLAIMER</Typography>
      <Typography>The Tool is designed to simulate conversations and interactions for entertainment and role-playing purposes. However, because it uses algorithmic models to generate speech, it may create dialogues that are unpredictable, offensive, or otherwise inappropriate. The Licensor does not endorse, condone, or assume any responsibility for any offensive, harmful, or profane content generated by the Tool during use. You acknowledge that the conversations produced by the Tool may not always align with appropriate standards of communication.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>4. COPYRIGHT AND INTELLECTUAL PROPERTY RIGHTS</Typography>
      <Typography>The Tool, including all code, designs, user interfaces, and any other associated intellectual property, is owned by the Licensor and is protected by copyright laws and other intellectual property rights. All rights not expressly granted to you under this Agreement are reserved by the Licensor. You may not modify, decompile, reverse-engineer, disassemble, or create derivative works based on the Tool without the express written consent of the Licensor.</Typography>
      <Typography>You are strictly prohibited from distributing, copying, or sharing the Tool through any unlicensed gateways, platforms, or peer-to-peer networks. Unauthorized distribution of the Tool or any portions thereof is a violation of this Agreement and may result in legal action.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>5. PROHIBITED USES</Typography>
      <Typography>The following uses of the Tool are strictly prohibited:</Typography>
      <Typography>Using the Tool to impersonate real people, including public figures, celebrities, or private individuals, without their consent.</Typography>
      <Typography>Using the Tool to create, distribute, or transmit any unlawful, harmful, threatening, defamatory, obscene, offensive, or otherwise objectionable material.</Typography>
      <Typography>Using the Tool to infringe upon the intellectual property rights, privacy, or rights of publicity of any third party.</Typography>
      <Typography>Porting the Tool to any platform or gateway that has not been licensed by the Licensor.</Typography>
      <Typography>Sharing or distributing the Tool in a manner that circumvents its licensing restrictions, including but not limited to piracy or unauthorized modifications.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>6. LIABILITY FOR PIRACY AND UNLICENSED DISTRIBUTION</Typography>
      <Typography>You agree that if you are found to be involved in the piracy, illegal copying, or distribution of the Tool through unlicensed or unauthorized channels, you will be held liable for any damages incurred by the Licensor. This includes, but is not limited to, financial damages, legal costs, and any penalties imposed by applicable laws. The Licensor reserves the right to pursue legal action against any individuals or entities found in violation of this Agreement.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>7. NO WARRANTY</Typography>
      <Typography>The Tool is provided "as is" without any warranties, express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, or non-infringement. The Licensor does not guarantee that the Tool will be free from defects, errors, or interruptions and will not be liable for any damages, loss of data, or other consequences arising from its use.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>8. LIMITATION OF LIABILITY</Typography>
      <Typography>To the fullest extent permitted by applicable law, in no event shall the Licensor be liable for any indirect, incidental, consequential, special, punitive, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data, or other intangible losses, even if the Licensor has been advised of the possibility of such damages, resulting from:</Typography>
      <Typography>The use or inability to use the Tool.</Typography>
      <Typography>The unauthorized access to or alteration of your data.</Typography>
      <Typography>Any other matter relating to the Tool.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>9. TERMINATION</Typography>
      <Typography>This Agreement is effective until terminated. The Licensor may terminate this Agreement at any time if you breach any of the terms herein. Upon termination, you must cease all use of the Tool and destroy any copies in your possession.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>10. GOVERNING LAW</Typography>
      <Typography>This Agreement shall be governed by and construed in accordance with the laws of Brazil, without regard to its conflict of laws principles. You agree that any legal action arising out of or relating to this Agreement shall be brought exclusively in the courts of Brazil.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>11. ENTIRE AGREEMENT</Typography>
      <Typography>This Agreement constitutes the entire agreement between you and the Licensor concerning the Tool and supersedes any prior agreements, discussions, or representations. No amendment or modification of this Agreement will be binding unless made in writing and signed by the Licensor.</Typography>

    <Typography variant='h6' className='p-4 pt-8'>12. CONTACT INFORMATION</Typography>
      <Typography>For any questions, concerns, or inquiries regarding this Agreement, please contact:</Typography>
      <Typography>Tomás de Lima</Typography>
      <Typography>Email: tomasdelima@yahoo.com.br</Typography>
  </Box>
}

export default TermsAndConditions
